### ISSUE TITLE
As an Event Planner, I can list all persons and tasks

### ISSUE THREAD

**Issue by jiakai-17** [AY2324S1-CS2103T-T10-2/tp#111]
... so that I can quickly see all my persons and tasks.

Tasks:
- Implement `listAll` command that lists all persons and tasks, similar to clearing all search filters from the `find*` commands

**Comment by HugeNoob** [comment]
Have you added the new command to the UG? If so, you can close this again.

**Comment by jiakai-17** [comment]
Added to UG in https://github.com/AY2324S1-CS2103T-T10-2/tp/pull/108/commits/55cd37e99245b0c298c8082ce2b1810eafe8b06e
