### ISSUE TITLE
[PE-D][Tester C] Feature: inconsistent delete command behaviour

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T10-2/tp#141]
# Description
- Regular delete commands do not reset the list after deletion
- `deleteAllDone` command will reset the list after deletion

# Implications
- This can be quite confusing as a user when trying to delete multiple things

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Kurtyjlee/ped#7

**Comment by jiakai-17** [comment]
We plan to standardise the behaviour of `delete*` commands in a future update.
