### ISSUE TITLE
[PE-D][Tester D] Suggestion - Implementation of Case-Insensitive Command Keywords

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T10-2/tp#142]
The current system enforces case-sensitive command keywords, which can slow down user input.

With the suggested change, the following command variations would all be treated identically:

- `addPerson`
- `addperson`

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: iyioon/ped#5

**Comment by jiakai-17** [comment]
Already implemented as aliases, but not documented in UG yet
