### ISSUE TITLE
Update User Guide

### ISSUE THREAD

**Issue by jiakai-17** [AY2324S1-CS2103T-T10-2/tp#38]
https://nus-cs2103-ay2324s1.github.io/website/schedule/week7/project.html#3-update-the-ug

Tasks:
- [ ] Update the old UG with draft version
- [ ] Update the content of the UG

**Comment by HugeNoob** [comment]
![image](https://github.com/AY2324S1-CS2103T-T10-2/tp/assets/65714641/ca9ce67b-2371-4490-9965-2b4a63c627c9)

Description here seems to be wrong. `deleteTask` but mentioned deleting contact.

**Comment by HugeNoob** [comment]
Is it possible for all drawings to also show the commands associated? Would be clearer for the user. I noticed this for a few other drawings as well.

![image](https://github.com/AY2324S1-CS2103T-T10-2/tp/assets/65714641/7f43c78a-42fe-4176-b581-4a9b2ca9395a)
